// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWa2s-_0gJyoHNvQyFiHg_Tvn5xWJqtjo',
    appId: '1:347926203819:web:8c2e1262fc351328fcd6ee',
    messagingSenderId: '347926203819',
    projectId: 'sports-event-app-589dc',
    authDomain: 'sports-event-app-589dc.firebaseapp.com',
    storageBucket: 'sports-event-app-589dc.firebasestorage.app',
    measurementId: 'G-QHQC126LM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxf66Gif2fJaH0CMJcmnelCCROJvA9jo',
    appId: '1:347926203819:android:8b57bbee483d334efcd6ee',
    messagingSenderId: '347926203819',
    projectId: 'sports-event-app-589dc',
    storageBucket: 'sports-event-app-589dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDImM0Dp3p5ycasYK2C-XXoewcfrAcaVQo',
    appId: '1:347926203819:ios:4cd90766e2cfa00cfcd6ee',
    messagingSenderId: '347926203819',
    projectId: 'sports-event-app-589dc',
    storageBucket: 'sports-event-app-589dc.firebasestorage.app',
    iosBundleId: 'com.example.sportsEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWa2s-_0gJyoHNvQyFiHg_Tvn5xWJqtjo',
    appId: '1:347926203819:web:90543eda944f3eedfcd6ee',
    messagingSenderId: '347926203819',
    projectId: 'sports-event-app-589dc',
    authDomain: 'sports-event-app-589dc.firebaseapp.com',
    storageBucket: 'sports-event-app-589dc.firebasestorage.app',
    measurementId: 'G-9ZKMH1C8DX',
  );
}