// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnRLOZuTyGZK6Gz6nF5K9l7fKldJPYffw',
    appId: '1:951485937829:web:ca2c9f0fb68afafae1f54c',
    messagingSenderId: '951485937829',
    projectId: 'sports-event-app-2025',
    authDomain: 'sports-event-app-2025.firebaseapp.com',
    storageBucket: 'sports-event-app-2025.firebasestorage.app',
    measurementId: 'G-Z2XC2C86VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk4kH4ZZq_tfnfKDtPgWxoPgpWe5UABkI',
    appId: '1:951485937829:android:f58b2e97b3275df6e1f54c',
    messagingSenderId: '951485937829',
    projectId: 'sports-event-app-2025',
    storageBucket: 'sports-event-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSSpuhcVoojZZPnGImZaYrfHrAgjGKiw',
    appId: '1:951485937829:ios:b140cb4e54c37136e1f54c',
    messagingSenderId: '951485937829',
    projectId: 'sports-event-app-2025',
    storageBucket: 'sports-event-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.sportsEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiSSpuhcVoojZZPnGImZaYrfHrAgjGKiw',
    appId: '1:951485937829:ios:b140cb4e54c37136e1f54c',
    messagingSenderId: '951485937829',
    projectId: 'sports-event-app-2025',
    storageBucket: 'sports-event-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.sportsEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnRLOZuTyGZK6Gz6nF5K9l7fKldJPYffw',
    appId: '1:951485937829:web:fc60d538a6af956be1f54c',
    messagingSenderId: '951485937829',
    projectId: 'sports-event-app-2025',
    authDomain: 'sports-event-app-2025.firebaseapp.com',
    storageBucket: 'sports-event-app-2025.firebasestorage.app',
    measurementId: 'G-723F3F73Y4',
  );

}